name: Go package
permissions:
  contents: write
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build For several platform
        run: |
          go get .
          GOOS=linux GOARCH=amd64 go build -o build/go-parse-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o build/go-parse-darwin-amd64
          GOOS=darwin GOARCH=amd64 go build -o build/go-parse-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o build/go-parse-win-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o build/go-parse-win-arm64.exe


      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/go-parse-linux-amd64
            build/go-parse-darwin-amd64
            build/go-parse-darwin-arm64
            build/go-parse-win-amd64.exe
            build/go-parse-win-arm64.exe
