name: Go package

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build For several platform
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/liunx/go-parse
          GOOS=darwin GOARCH=amd64 go build -o build/darwin/amd64/go-parse
          GOOS=darwin GOARCH=amd64 go build -o build/darwin/arm64/go-parse
          GOOS=windows GOARCH=amd64 go build -o build/windows/go-parse.exe

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            build/linux/go-parse
            build/darwin/amd64/go-parse
            build/darwin/arm64/go-parse
            build/windows/go-parse.exe

